#                   _
#                  (_)
#   _   _  __ _ _____
#  | | | |/ _` |_  / |
#  | |_| | (_| |/ /| |
#   \__, |\__,_/___|_|
#    __/ |
#   |___/

[mgr]
show_hidden  = true
show_symlink = true
