[packages.common]
apps = ['1password', '1password-cli']
tools = [
  'act',
  'atuin',
  'bat',
  'bob',
  'btop',
  'buf',
  'chezmoi',
  'cmake',
  'curl',
  'eza',
  'fd',
  'fish',
  'fvm',
  'fzf',
  'git',
  'glow',
  'gnupg',
  'golangci-lint',
  'helm',
  'hurl',
  'jq',
  'lazydocker',
  'lazygit',
  'lsof',
  'ripgrep',
  'slides',
  'sqlc',
  'starship',
  'tree',
  'tree-sitter',
  'tree-sitter-cli',
  'uv',
  'wget',
  'yazi',
  'zellij',
  'zoxide',
  'zsh',
]
