[packages.homebrew]
taps = ['hashicorp/tap', 'jannis-baum/tap', 'leoafarias/fvm', 'microsoft/git', 'nikitabobko/tap', 'teamookla/speedtest']
formula = [
  'awscli',
  'azure-cli',
  'dotenv-linter',
  'fvm',
  'git',
  'gnu-sed',
  'gnupg',
  'kubernetes-cli',
  'libpq',
  'mas',
  'mise',
  'openssl',
  'readline',
  'redis',
  'rustup',
  'shfmt',
  'speedtest',
  'sqlite3',
  'tcl-tk',
  'terraform',
  'zlib',
  'zsh',
]
casks = [
  '1password-cli',
  'aerospace',
  'bartender',
  'elgato-camera-hub',
  'flutter',
  'font-jetbrains-mono',
  'font-jetbrains-mono-nerd-font',
  'font-symbols-only-nerd-font',
  'git-credential-manager',
  'karabiner-elements',
  'obs',
  'orbstack',
  'pocket-casts',
  'raycast',
  'session-manager-plugin',
  'shottr',
  'slack',
  'spotify',
  'tableplus',
  'thunderbird@esr',
  'visual-studio-code',
  'vlc',
  'wezterm@nightly',
  'zed',
  'zen',
  'zoom',
]
