[packages.yay]
apps = ['obs-studio', 'obsidian', 'spotify', 'thunderbird', 'vlc', 'zed', 'zen-browser-bin', 'zoom']
tools = [
  'amazon-ecr-credential-helper',
  'aws-cli-bin',
  'aws-sam-cli-bin',
  'aws-session-manager-plugin',
  'azure-cli',
  'docker',
  'docker-compose',
  'fastfetch',
  'fvm',
  'git',
  'github-cli',
  'gnupg',
  'kubectl',
  'man-db',
  'man-pages',
  'minikube',
  'ookla-speedtest-bin',
  'swappy',
  'swaync',
  'terraform',
  'ttf-jetbrains-mono',
  'ttf-jetbrains-mono-nerd',
  'ttf-nerd-fonts-symbols-mono',
  'v4l2loopback-utils',
  'vivify-bin',
  'wl-clip-persist',
  'wl-clipboard',
  'yazi',
  'zellij',
  'zoxide',
]
