#             _                                       _
#            (_)                                     | |
#   _ __ ___  _ ___  ___ ______ ___ _ __ ______ _ __ | | __ _  ___ ___
#  | '_ ` _ \| / __|/ _ \______/ _ \ '_ \______| '_ \| |/ _` |/ __/ _ \
#  | | | | | | \__ \  __/     |  __/ | | |     | |_) | | (_| | (_|  __/
#  |_| |_| |_|_|___/\___|      \___|_| |_|     | .__/|_|\__,_|\___\___|
#                                              | |
#                                              |_|


[settings]
env_file                            = ".env"
experimental                        = true
go_default_packages_file            = "~/.config/mise/golang"
idiomatic_version_file_enable_tools = ["go", "node", "python", "ruby"]

[settings.python]
compile               = false
default_packages_file = "~/.config/mise/python"

[settings.ruby]
default_packages_file = "~/.config/mise/ruby"

[tools.bun]
version = "1.3"

[tools.go]
version = "1.25"

[tools.node]
version = "lts"

[tools.python]
version = "3.14"

[tools.ruby]
version = "3.4"

[tools.rust]
version    = "stable"
components = "rust-analyzer"

[tools.zig]
version = "0.15"
