#             _                                       _
#            (_)                                     | |
#   _ __ ___  _ ___  ___ ______ ___ _ __ ______ _ __ | | __ _  ___ ___
#  | '_ ` _ \| / __|/ _ \______/ _ \ '_ \______| '_ \| |/ _` |/ __/ _ \
#  | | | | | | \__ \  __/     |  __/ | | |     | |_) | | (_| | (_|  __/
#  |_| |_| |_|_|___/\___|      \___|_| |_|     | .__/|_|\__,_|\___\___|
#                                              | |
#                                              |_|


[tools]
bun    = { version = "1.3" }
deno   = { version = "2" }
go     = { version = "1.25" }
node   = { version = "lts" }
python = { version = "3.14" }
ruby   = { version = "3.4" }
rust   = { version = "stable", profile = "default", components = "rust-analyzer" }
zig    = { version = "0.15" }

[settings]
env_file                            = ".env"
experimental                        = true
go_default_packages_file            = "~/.config/mise/golang"
idiomatic_version_file_enable_tools = ["go", "node", "python", "ruby"]

[settings.python]
default_packages_file = "~/.config/mise/python"
compile               = false

[settings.ruby]
default_packages_file = "~/.config/mise/ruby"
