#   _                     _            _
#  | |                   | |          | |
#  | | __ _ _____   _  __| | ___   ___| | _____ _ __
#  | |/ _` |_  / | | |/ _` |/ _ \ / __| |/ / _ \ '__|
#  | | (_| |/ /| |_| | (_| | (_) | (__|   <  __/ |
#  |_|\__,_/___|\__, |\__,_|\___/ \___|_|\_\___|_|
#                __/ |
#               |___/

gui:
  border: "single"
  showBottomLine: false
